name: Generate page
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-tutorial-sync
      - trigger-document-sync
  pull_request:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Configure Git Credentials
        run: |
          git config user.name yunwei37
          git config user.email yunwei356@gmail.com
          git submodule update --init --recursive
      - name: Install all
        run: |
          make
      - name: Commit changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update for modify contents" && git push)
      
      - name: Build page
        if: github.event_name == 'pull_request'
        run: |
          mkdocs build -v

      - name: Deploy page
        if: |
          github.event_name == 'repository_dispatch' ||
          github.event_name == 'push' ||
          github.event_name == 'workflow_dispatch'
        run: |
          mkdocs gh-deploy -m "{sha}"  --force 
