name: Legacy MkDocs Build
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Configure Git Credentials
        run: |
          git config user.name yunwei37
          git config user.email yunwei356@gmail.com
          git submodule update --init --recursive
      - name: Install all
        run: |
          make
